In [1]:
import pandas as pd

clonality_df = pd.read_csv("combined_clonality.csv")

clonality_df.head(10)

FileNotFoundError: [Errno 2] File b'combined_clonality.csv' does not exist: b'combined_clonality.csv'

In [26]:
line_counts_df = pd.read_csv("line_counts.csv")

line_counts_df["line_count"] = line_counts_df["line_count"] / 4
line_counts_df.head(10)

                  SAMPLE   line_count
0  HH001_A1_SA_S1_R1_001   87147897.0
1  HH001_B1_SA_S2_R1_001   82613923.0
2  HH001_B3_SA_S3_R1_001  193979940.0
3  HH003_A1_SA_S4_R1_001  212200004.0
4  HH003_A3_SA_S5_R1_001   97778641.0
5  HH003_B3_SA_S6_R1_001   75234983.0
6   HH003_D_SA_S7_R1_001   63623783.0
7   HH003_K_SA_S8_R1_001   39694161.0
8   HH003_R_SA_S9_R1_001   15125472.0

In [27]:
merged_clonality_df=pd.merge(clonality_df, line_counts_df, on='SAMPLE')
merged_clonality_df.head(10)

,SAMPLE,nIGH,nIGK,nIGL,nTCRA,nTCRB,nTCRD,nTCRG,loadIGH,loadIGK,...,loadTCRD,loadTCRG,alphaIGH,alphaIGK,alphaIGL,alphaTCRA,alphaTCRB,alphaTCRD,alphaTCRG,line_count
0,HH001_B1_SA_S2_R1_001,4,25,2,14,0,0,0,10,78,...,0,0,1.332179,2.963446,0.636514,2.465535,0,0,0,82613923.0
1,HH001_B3_SA_S3_R1_001,12,59,8,17,0,0,0,30,267,...,0,0,2.375192,3.277293,2.059229,2.594020,0,0,0,193979940.0
2,HH003_A1_SA_S4_R1_001,0,0,1,20,0,0,0,0,0,...,0,0,0.000000,0.000000,-0.000000,2.147085,0,0,0,212200004.0
3,HH003_A3_SA_S5_R1_001,0,0,0,13,0,0,0,0,0,...,0,0,0.000000,0.000000,0.000000,2.152679,0,0,0,97778641.0
4,HH003_B3_SA_S6_R1_001,0,0,0,18,0,0,0,0,0,...,0,0,0.000000,0.000000,0.000000,2.265151,0,0,0,75234983.0
5,HH003_D_SA_S7_R1_001,1,1,2,17,0,0,0,4,3,...,0,0,-0.000000,-0.000000,0.529706,2.208248,0,0,0,63623783.0
6,HH003_K_SA_S8_R1_001,0,0,0,10,0,0,0,0,0,...,0,0,0.000000,0.000000,0.000000,2.008140,0,0,0,39694161.0
7,HH003_R_SA_S9_R1_001,1,0,0,6,0,0,0,4,0,...,0,0,-0.000000,0.000000,0.000000,1.748971,0,0,0,15125472.0

# normalize

In [29]:
merged_clonality_df["nIGH"] = (merged_clonality_df["nIGH"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["nIGK"] = (merged_clonality_df["nIGK"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["nIGL"] = (merged_clonality_df["nIGL"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["nTCRA"] = (merged_clonality_df["nTCRA"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["nTCRB"] = (merged_clonality_df["nTCRB"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["nTCRD"] = (merged_clonality_df["nTCRD"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["nTCRG"] = (merged_clonality_df["nTCRG"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["loadIGH"] = (merged_clonality_df["loadIGH"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["loadIGK"] = (merged_clonality_df["loadIGK"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["loadIGL"] = (merged_clonality_df["loadIGL"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["loadTCRA"] = (merged_clonality_df["loadTCRA"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["loadTCRB"] = (merged_clonality_df["loadTCRB"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["loadTCRD"] = (merged_clonality_df["loadTCRD"] / merged_clonality_df["line_count"]) * 1000000
merged_clonality_df["loadTCRG"] = (merged_clonality_df["loadTCRG"] / merged_clonality_df["line_count"]) * 1000000

merged_clonality_df.head(10)

,SAMPLE,nIGH,nIGK,nIGL,nTCRA,nTCRB,nTCRD,nTCRG,loadIGH,loadIGK,...,loadTCRD,loadTCRG,alphaIGH,alphaIGK,alphaIGL,alphaTCRA,alphaTCRB,alphaTCRD,alphaTCRG,line_count
0,HH001_B1_SA_S2_R1_001,0.000586,0.003663,0.000293,0.002051,0.0,0.0,0.0,0.121045,0.944151,...,0.0,0.0,1.332179,2.963446,0.636514,2.465535,0,0,0,82613923.0
1,HH001_B3_SA_S3_R1_001,0.000319,0.001568,0.000213,0.000452,0.0,0.0,0.0,0.154655,1.376431,...,0.0,0.0,2.375192,3.277293,2.059229,2.594020,0,0,0,193979940.0
2,HH003_A1_SA_S4_R1_001,0.000000,0.000000,0.000022,0.000444,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,-0.000000,2.147085,0,0,0,212200004.0
3,HH003_A3_SA_S5_R1_001,0.000000,0.000000,0.000000,0.001360,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,2.152679,0,0,0,97778641.0
4,HH003_B3_SA_S6_R1_001,0.000000,0.000000,0.000000,0.003180,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,2.265151,0,0,0,75234983.0
5,HH003_D_SA_S7_R1_001,0.000247,0.000247,0.000494,0.004200,0.0,0.0,0.0,0.062870,0.047152,...,0.0,0.0,-0.000000,-0.000000,0.529706,2.208248,0,0,0,63623783.0
6,HH003_K_SA_S8_R1_001,0.000000,0.000000,0.000000,0.006347,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.000000,2.008140,0,0,0,39694161.0
7,HH003_R_SA_S9_R1_001,0.004371,0.000000,0.000000,0.026226,0.0,0.0,0.0,0.264455,0.000000,...,0.0,0.0,-0.000000,0.000000,0.000000,1.748971,0,0,0,15125472.0

In [33]:
merged_clonality_df.to_csv('annie_normalized_clonality.csv',index=False)